"""Inicial

Revision ID: f221e54b4584
Revises: 
Create Date: 2025-08-21 09:24:21.628493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f221e54b4584'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('termino', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=200), nullable=False),
    sa.Column('term_es', sa.Text(), nullable=False),
    sa.Column('term_en', sa.Text(), nullable=False),
    sa.Column('term_fr', sa.Text(), nullable=False),
    sa.Column('ejemplo1_es', sa.Text(), nullable=True),
    sa.Column('ejemplo1_en', sa.Text(), nullable=True),
    sa.Column('ejemplo1_fr', sa.Text(), nullable=True),
    sa.Column('ejemplo2_es', sa.Text(), nullable=True),
    sa.Column('ejemplo2_en', sa.Text(), nullable=True),
    sa.Column('ejemplo2_fr', sa.Text(), nullable=True),
    sa.Column('fuente', sa.String(length=400), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term')
    # ### end Alembic commands ###
